import type { AtmosphereId } from '@/data/bands'

/**
 * Generate a loopable noise buffer and start it through a low-pass filter.
 * Pure synthesis from white noise — no audio assets needed for M1.
 *
 * - Pink noise (1/f): -3 dB/oct. Generated via the Voss–McCartney stacking
 *   algorithm approximated by a cascade first-order low-pass on white noise.
 * - Brown noise (1/f²): -6 dB/oct. Generated by integrating white noise.
 *
 * Both outputs are peak-ish normalized and passed through a low-pass
 * BiquadFilterNode so the top end is tamed (appspec §5.2 atmosphere chain).
 */
export interface AtmosphereEngine {
  source: AudioBufferSourceNode
  filter: BiquadFilterNode
  gain: GainNode
}

function makeNoiseBuffer(ctx: AudioContext, profile: 'pink' | 'brown'): AudioBuffer {
  const seconds = 4
  const length = Math.floor(ctx.sampleRate * seconds)
  const buffer = ctx.createBuffer(2, length, ctx.sampleRate)
  const white = new Float32Array(length)

  for (let i = 0; i < length; i++) white[i] = Math.random() * 2 - 1

  if (profile === 'pink') {
    // Paul Kellet's refined pink filter (standard implementation).
    const b0 = 0.99886
    const b1 = 0.99332
    const b2 = 0.969
    const b3 = 0.8665
    const b5 = -0.7616
    let s0 = 0,
      s1 = 0,
      s2 = 0,
      s3 = 0
    for (let ch = 0; ch < 2; ch++) {
      const data = buffer.getChannelData(ch)
      for (let i = 0; i < length; i++) {
        const w = white[i]
        s0 = b0 * s0 + w * 0.99886
        s1 = b1 * s1 + w * 0.99332
        s2 = b2 * s2 + w * 0.969
        s3 = b3 * s3 + w * 0.8665
        const out = (s0 + s1 + s2 + s3 + w * b5) * 0.11
        data[i] = out
      }
    }
  } else {
    // Brown noise: integrate white noise (Leaky integrator).
    for (let ch = 0; ch < 2; ch++) {
      const data = buffer.getChannelData(ch)
      let last = 0
      for (let i = 0; i < length; i++) {
        const out = (last + 0.02 * white[i]) / 1.02
        last = out
        data[i] = out * 3.5
      }
    }
  }

  // Normalize each channel to approx -3 dBFS peak to keep levels predictable.
  for (let ch = 0; ch < 2; ch++) {
    const data = buffer.getChannelData(ch)
    let peak = 0
    for (let i = 0; i < length; i++) peak = Math.max(peak, Math.abs(data[i]))
    if (peak > 0) {
      const scale = 0.7 / peak
      for (let i = 0; i < length; i++) data[i] *= scale
    }
  }

  return buffer
}

export function createAtmosphere(ctx: AudioContext, id: AtmosphereId): AtmosphereEngine {
  const profile: 'pink' | 'brown' = id === 'pink' ? 'pink' : 'brown'
  const buffer = makeNoiseBuffer(ctx, profile)

  const source = ctx.createBufferSource()
  source.buffer = buffer
  source.loop = true

  const filter = ctx.createBiquadFilter()
  filter.type = 'lowpass'
  filter.frequency.value = 3000
  filter.Q.value = 0.3

  const gain = ctx.createGain()
  gain.gain.value = 0

  source.connect(filter).connect(gain)
  source.start()

  return { source, filter, gain }
}
